INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇨', 'Ascension Island');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇩', 'Andorra');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇪', 'United Arab Emirates');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇫', 'Afghanistan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇬', 'Antigua & Barbuda');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇮', 'Anguilla');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇱', 'Albania');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇲', 'Armenia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇴', 'Angola');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇶', 'Antarctica');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇷', 'Argentina');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇸', 'American Samoa');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇹', 'Austria');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇺', 'Australia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇼', 'Aruba');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇽', 'Åland Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇦🇿', 'Azerbaijan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇦', 'Bosnia & Herzegovina');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇧', 'Barbados');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇩', 'Bangladesh');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇪', 'Belgium');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇫', 'Burkina Faso');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇬', 'Bulgaria');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇭', 'Bahrain');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇮', 'Burundi');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇯', 'Benin');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇱', 'St. Barthélemy');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇲', 'Bermuda');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇳', 'Brunei');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇴', 'Bolivia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇶', 'Caribbean Netherlands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇷', 'Brazil');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇸', 'Bahamas');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇹', 'Bhutan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇻', 'Bouvet Island');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇼', 'Botswana');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇾', 'Belarus');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇧🇿', 'Belize');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇦', 'Canada');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇨', 'Cocos (Keeling) Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇩', 'Congo - Kinshasa');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇫', 'Central African Republic');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇬', 'Congo - Brazzaville');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇭', 'Switzerland');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇮', 'Côte d’Ivoire');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇰', 'Cook Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇱', 'Chile');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇲', 'Cameroon');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇳', 'China');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇴', 'Colombia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇵', 'Clipperton Island');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇷', 'Costa Rica');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇺', 'Cuba');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇻', 'Cape Verde');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇼', 'Curaçao');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇽', 'Christmas Island');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇾', 'Cyprus');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇨🇿', 'Czechia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇩🇪', 'Germany');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇩🇬', 'Diego Garcia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇩🇯', 'Djibouti');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇩🇰', 'Denmark');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇩🇲', 'Dominica');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇩🇴', 'Dominican Republic');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇩🇿', 'Algeria');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇪🇦', 'Ceuta & Melilla');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇪🇨', 'Ecuador');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇪🇪', 'Estonia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇪🇬', 'Egypt');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇪🇭', 'Western Sahara');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇪🇷', 'Eritrea');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇪🇸', 'Spain');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇪🇹', 'Ethiopia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇪🇺', 'European Union');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇫🇮', 'Finland');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇫🇯', 'Fiji');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇫🇰', 'Falkland Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇫🇲', 'Micronesia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇫🇴', 'Faroe Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇫🇷', 'France');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇦', 'Gabon');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇧', 'United Kingdom');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇩', 'Grenada');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇪', 'Georgia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇫', 'French Guiana');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇬', 'Guernsey');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇭', 'Ghana');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇮', 'Gibraltar');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇱', 'Greenland');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇲', 'Gambia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇳', 'Guinea');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇵', 'Guadeloupe');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇶', 'Equatorial Guinea');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇷', 'Greece');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇸', 'South Georgia & South Sandwich Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇹', 'Guatemala');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇺', 'Guam');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇼', 'Guinea-Bissau');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇬🇾', 'Guyana');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇭🇰', 'Hong Kong SAR China');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇭🇲', 'Heard & McDonald Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇭🇳', 'Honduras');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇭🇷', 'Croatia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇭🇹', 'Haiti');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇭🇺', 'Hungary');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇮🇨', 'Canary Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇮🇩', 'Indonesia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇮🇪', 'Ireland');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇮🇱', 'Israel');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇮🇲', 'Isle of Man');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇮🇳', 'India');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇮🇴', 'British Indian Ocean Territory');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇮🇶', 'Iraq');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇮🇷', 'Iran');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇮🇸', 'Iceland');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇮🇹', 'Italy');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇯🇪', 'Jersey');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇯🇲', 'Jamaica');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇯🇴', 'Jordan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇯🇵', 'Japan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇰🇪', 'Kenya');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇰🇬', 'Kyrgyzstan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇰🇭', 'Cambodia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇰🇮', 'Kiribati');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇰🇲', 'Comoros');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇰🇳', 'St. Kitts & Nevis');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇰🇵', 'North Korea');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇰🇷', 'South Korea');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇰🇼', 'Kuwait');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇰🇾', 'Cayman Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇰🇿', 'Kazakhstan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇱🇦', 'Laos');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇱🇧', 'Lebanon');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇱🇨', 'St. Lucia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇱🇮', 'Liechtenstein');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇱🇰', 'Sri Lanka');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇱🇷', 'Liberia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇱🇸', 'Lesotho');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇱🇹', 'Lithuania');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇱🇺', 'Luxembourg');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇱🇻', 'Latvia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇱🇾', 'Libya');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇦', 'Morocco');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇨', 'Monaco');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇩', 'Moldova');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇪', 'Montenegro');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇫', 'St. Martin');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇬', 'Madagascar');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇭', 'Marshall Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇰', 'North Macedonia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇱', 'Mali');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇲', 'Myanmar (Burma)');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇳', 'Mongolia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇴', 'Macao SAR China');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇵', 'Northern Mariana Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇶', 'Martinique');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇷', 'Mauritania');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇸', 'Montserrat');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇹', 'Malta');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇺', 'Mauritius');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇻', 'Maldives');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇼', 'Malawi');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇽', 'Mexico');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇾', 'Malaysia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇲🇿', 'Mozambique');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇳🇦', 'Namibia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇳🇨', 'New Caledonia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇳🇪', 'Niger');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇳🇫', 'Norfolk Island');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇳🇬', 'Nigeria');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇳🇮', 'Nicaragua');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇳🇱', 'Netherlands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇳🇴', 'Norway');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇳🇵', 'Nepal');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇳🇷', 'Nauru');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇳🇺', 'Niue');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇳🇿', 'New Zealand');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇴🇲', 'Oman');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇦', 'Panama');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇪', 'Peru');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇫', 'French Polynesia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇬', 'Papua New Guinea');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇭', 'Philippines');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇰', 'Pakistan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇱', 'Poland');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇲', 'St. Pierre & Miquelon');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇳', 'Pitcairn Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇷', 'Puerto Rico');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇸', 'Palestinian Territories');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇹', 'Portugal');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇼', 'Palau');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇵🇾', 'Paraguay');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇶🇦', 'Qatar');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇷🇪', 'Réunion');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇷🇴', 'Romania');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇷🇸', 'Serbia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇷🇺', 'Russia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇷🇼', 'Rwanda');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇦', 'Saudi Arabia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇧', 'Solomon Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇨', 'Seychelles');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇩', 'Sudan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇪', 'Sweden');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇬', 'Singapore');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇭', 'St. Helena');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇮', 'Slovenia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇯', 'Svalbard & Jan Mayen');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇰', 'Slovakia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇱', 'Sierra Leone');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇲', 'San Marino');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇳', 'Senegal');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇴', 'Somalia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇷', 'Suriname');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇸', 'South Sudan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇹', 'São Tomé & Príncipe');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇻', 'El Salvador');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇽', 'Sint Maarten');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇾', 'Syria');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇸🇿', 'Eswatini');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇦', 'Tristan da Cunha');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇨', 'Turks & Caicos Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇩', 'Chad');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇫', 'French Southern Territories');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇬', 'Togo');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇭', 'Thailand');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇯', 'Tajikistan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇰', 'Tokelau');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇱', 'Timor-Leste');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇲', 'Turkmenistan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇳', 'Tunisia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇴', 'Tonga');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇷', 'Turkey');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇹', 'Trinidad & Tobago');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇻', 'Tuvalu');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇼', 'Taiwan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇹🇿', 'Tanzania');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇺🇦', 'Ukraine');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇺🇬', 'Uganda');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇺🇲', 'U.S. Outlying Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇺🇳', 'United Nations');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇺🇸', 'United States');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇺🇾', 'Uruguay');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇺🇿', 'Uzbekistan');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇻🇦', 'Vatican City');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇻🇨', 'St. Vincent & Grenadines');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇻🇪', 'Venezuela');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇻🇬', 'British Virgin Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇻🇮', 'U.S. Virgin Islands');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇻🇳', 'Vietnam');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇻🇺', 'Vanuatu');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇼🇫', 'Wallis & Futuna');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇼🇸', 'Samoa');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇽🇰', 'Kosovo');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇾🇪', 'Yemen');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇾🇹', 'Mayotte');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇿🇦', 'South Africa');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇿🇲', 'Zambia');
INSERT INTO `country` (`flag_unicode`, `name`) VALUES ('🇿🇼', 'Zimbabwe');
